const config = {
    margin: {
        top: 20,
        right: 30,
        bottom: 150,
        left: 50
    },
    lineChart: {
        width: 720,
        height: 320
    },
    dataset: {
        aggregatedPath: "data/aggr_genre_sum.csv",
        actionPath : "data/genres/action.csv",
        adventurePath : "data/genres/adventure.csv",
        casualPath : "data/genres/casual.csv",
        educationPath : "data/genres/education.csv",
        racingPath : "data/genres/racing.csv",
        rpgPath : "data/genres/rpg.csv",
        simulationPath : "data/genres/simulation.csv",
        sportsPath : "data/genres/sports.csv",
        strategyPath : "data/genres/strategy.csv"
    },
    timeAttributes: [ // Deprecated, but still used.
        "January 2019",
        "February 2019",
        "March 2019",
        "April 2019",
        "May 2019",
        "June 2019",
        "July 2019",
        "August 2019",
        "September 2019",
        "October 2019",
        "November 2019",
        "December 2019",
        "January 2020",
        "February 2020",
        "March 2020",
        "April 2020",
        "May 2020",
        "June 2020",
        "July 2020",
        "August 2020",
        "September 2020",
        "October 2020",
        "November 2020",
        "December 2020",
        "January 2021",
        "February 2021",
        "March 2021",
        "April 2021",
        "May 2021",
        "June 2021",
        "July 2021",
        "August 2021",
        "September 2021",
        "October 2021",
        "November 2021",
        "December 2021",
        "January 2022",
        "February 2022",
        "March 2022",
        "April 2022",
        "May 2022",
        "June 2022",
        "July 2022",
        "August 2022",
        "September 2022",
        "October 2022",
        "November 2022",
        "December 2022"
    ],
    genres: [
        "Action",
        "Adventure",
        "Casual",
        "Education",
        "RPG",
        "Racing",
        "Simulation",
        "Sports",
        "Strategy"
    ],
    month: {
        data: [
            "JAN",
            "FEB",
            "MAR",
            "APR",
            "MEI",
            "JUN",
            "JUL",
            "AGU",
            "SEP",
            "OKT",
            "NOV",
            "DES",
        ],
        default: "DES"
    },
    year: {
        data: [
            "2019",
            "2020",
            "2021",
            "2022"
        ],
        default: "2022"
    }
}
